### PR TITLE
Added display of estimated battery life

### PR DESCRIPTION
**Pull request by rkuchkarov**

### CODE REVIEW

**Comment by rkuchkarov** [comment]
2023072700571900-02CB906EA538A35643C1E1484C4B947D

**Comment by masagrator** [comment]
This looks to me like if all CPU cores will be at 100% and with >= 1000 MHz CPU It will collide with GPU. Provide me a proof that it doesn't happen.

**Comment by rkuchkarov** [comment]
Yes, you're right. I tried to fix it just now in the latest commit. What do you think, is it acceptable?
The first screenshot - simultaneously the maximum length values
The second one - values of normal length that will most commonly occur

**Comment by masagrator** [comment]
Well, it looks ok. Few more things:
```c
remainingBatteryLife[5]
```
- increase to 6 for potential battery mods extending Life expectance to 10h+
- Eliminate space between time and power usage
- Optional (I will do it myself if you don't want): Add this information also into Battery/Charger mode with additional info about battery capacity (explicitly stating that if it's real or designed) 

And one question: do I see correctly you are reading max capacity all the time? If yes, write it so it will be done only once.

**Comment by rkuchkarov** [comment]
Okay, if I understood everything correctly, then everything should be ready now

**Comment by masagrator** [comment]
Sorry that I didn't fulfilled my word. I can't be now certain if I will be able to test it this month.

**Comment by rkuchkarov** [comment]
No problem. Do it whenever it's convenient for you

**Review by masagrator — APPROVED** [review]

**Comment by masagrator** [comment]
It looks ok. I will do some changes to layout after merging your PR + add one new feature to battery tab.

Thanks. :)

**Comment by rkuchkarov** [comment]
I was glad to contribute to your wonderful project :) I also thought about displaying the time until the battery is fully charged instead of [0:00] during charging, but I never got around to it. Maybe you would like to do it, but it doesn't seem so critical.

**Pull request merged**
